<?php

declare(strict_types=1);

const MAPS_PER_USER = 100;
const ELEMENTS_PER_MAP = 5000;
const PHOTOS_PER_ELEMENT = 10;
const MAX_PHOTO_BYTES = 5 * 1024 * 1024;
const MAX_VERTICES = 10000;
const MAX_MAP_NAME_LENGTH = 255;
const MAX_TEXT_LENGTH = 5000;
const DEFAULT_PAGE_SIZE = 50;
const MAX_PAGE_SIZE = 100;
const MAX_SEARCH_QUERY_LENGTH = 255;
const DELETE_ACCOUNT_CONFIRM_PHRASE = 'DELETE MY ACCOUNT';
