-- Client mutation ids are opaque strings generated by the browser
-- (`crypto.randomUUID()` on HTTPS, `mut-{ts}-{hex}` on plain HTTP).
ALTER TABLE client_mutations
    ALTER COLUMN client_mutation_id TYPE TEXT USING client_mutation_id::text;
